# datadog-agent.yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      serviceAccountName: datadog-agent
      hostNetwork: true
      containers:
        - image: 'datadog/agent:latest'
          imagePullPolicy: Always
          name: datadog-agent
          ports:

            ###############
            ## DogStatsD ##
            ###############
            - containerPort: 8125
              hostPort: 8125
              name: dogstatsdport
              protocol: UDP

            #########
            ## APM ##
            #########
            - containerPort: 8126
              hostPort: 8126
              name: traceport
              protocol: TCP
          env:
            ## The Datadog API Key related to your Organization set by secret
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-secret
                  key: api-key

            ## Set DD_SITE to 'datadoghq.eu' to send your Agent data to the Datadog EU site
            - name: DD_SITE
              value: 'datadoghq.com'

            #######################
            ## Metric collection ##
            #######################
            - name: KUBERNETES
              value: 'true'
            - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
              value: 'true'
            - name: DD_HEALTH_PORT
              value: '5555'
            - name: DD_COLLECT_KUBERNETES_EVENTS
              value: 'true'
            - name: DD_LEADER_ELECTION
              value: 'true'
            - name: DD_KUBELET_TLS_VERIFY
              value: 'false'
            - name: DD_KUBERNETES_KUBELET_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            ###############
            ## DogStatsD ##
            ###############
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              value: 'true'

            #########
            ## APM ##
            #########
            - name: DD_APM_ENABLED
              value: 'true'
            - name: DD_APM_NON_LOCAL_TRAFFIC
              value: 'true'
            - name: DD_APM_ENV
              value: "ruby-shop"
            - name: DD_TAGS
              value: "env:ruby-shop"

            ####################
            ## Log collection ##
            ####################
            - name: DD_LOGS_ENABLED
              value: 'true'
            - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
              value: 'true'
            - name: DD_AC_EXCLUDE
              value: 'name:datadog-agent'
            - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
              value: 'true'

            ########################
            ## Process collection ##
            ########################
            - name: DD_PROCESS_AGENT_ENABLED
              value: 'true'


          ## Note these are the minimum suggested values for requests and limits.
          ## The amount of resources required by the Agent varies depending on:
          ## * The number of checks
          ## * The number of integrations enabled
          ## * The number of features enabled
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m


          volumeMounts:

            #######################
            ## Metric collection ##
            #######################
            - name: dockersocketdir
              mountPath: /host/var/run/docker.sock
            - name: procdir
              mountPath: /host/proc
              readOnly: true
            - name: cgroups
              mountPath: /host/sys/fs/cgroup
              readOnly: true

            ####################
            ## Log collection ##
            ####################
            - name: pointdir
              mountPath: /opt/datadog-agent/run
            - name: logpodpath
              mountPath: /var/log/pods

              # Docker runtime directory, replace this path with your container runtime logs directory,
              # or remove this configuration if `/var/log/pods` is not a symlink to any other directory.
            - name: logcontainerpath
              mountPath: /var/lib/docker/containers

            ########################
            ## Process collection ##
            ########################
            - name: passwd
              mountPath: /etc/passwd
              readOnly: true

          livenessProbe:
            httpGet:
              path: /health
              port: 5555
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocketdir
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        #####################
        ## Log collection  ##
        #####################
        - hostPath:
            path: /var/lib/datadog-agent/logs
          name: pointdir
        - hostPath:
            path: /var/log/pods
          name: logpodpath
        # Docker runtime directory, replace this path with your container runtime logs directory,
        # or remove this configuration if `/var/log/pods` is not a symlink to any other directory.
        - hostPath:
            path: /var/lib/docker/containers
          name: logcontainerpath
        ########################
        ## Process collection ##
        ########################
        - hostPath:
            path: /etc/passwd
          name: passwd