#!/bin/bash
show_progress()
{
  sleep 0.5
  local -r pid="${1}"
  local -r delay='1'

  while true; do 
    grep -i "complete" /root/status.txt &> /dev/null
    if [[ "$?" -ne 0 ]]; then   
 
        sleep "${delay}" 
    else
      break
    fi
    
  done
}
# while [ ! -f "/root/status.txt" ]; do
#   sleep 0.3
# done
show_progress
# helm install datadogagent --set datadog.apiKey=$DD_API_KEY --set datadog.appKey=$DD_APP_KEY -f k8s-yaml-files/values.yaml stable/datadog
if [ ! -f "/root/provisioned" ]; then
  touch /root/provisioned
  printf "\n\nOK, the training environment is installed and ready to go.\n\n"
else
  printf "\n\nWelcome back to the training lab.\n\n"
fi
printf "Provisioning Complete\n\n"